[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "low_cost_bnn"
version = "0.0.1"
description = "Bayesian network network architecture with efficient approximative training"
readme = "README.md"
requires-python = ">=3.8"
license = {file = "LICENSE"}
keywords = ["sample", "setuptools", "development"]
authors = [
  {name = "Aaron Ho", email = "aaronkho@mit.edu" }
]
classifiers = [
  "Development Status :: 3 - Alpha",
  "Intended Audience :: Developers",
  "Topic :: Scientific/Engineering",
  "License :: OSI Approved :: MIT License",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3 :: Only",
]

dependencies = [
  "numpy",
  "scipy",
  "pandas",
  "scikit-learn"
]

[project.optional-dependencies]
dev = ["pytest", "coverage"]
tf = ["tensorflow", "tensorflow-probability[tf]"]
torch = ["torch"]

[project.urls]
"Homepage" = "https://github.com/aaronkho/low-cost-bnn"
"Bug Reports" = "https://github.com/aaronkho/low-cost-bnn/issues"
"Source" = "https://github.com/aaronkho/low-cost-bnn"

[project.scripts]
train_bnn_tf = "low_cost_bnn.workflows.train_tensorflow:main"
